# Generated by Django 3.2.6 on 2021-08-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlatesRlvd',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('camera_number', models.CharField(max_length=100)),
                ('junction_name', models.CharField(max_length=100)),
                ('evidence_camera_name', models.CharField(max_length=100)),
                ('number_plate_number', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('anpr_image', models.CharField(max_length=100)),
                ('xmin', models.CharField(max_length=50)),
                ('xmax', models.CharField(max_length=50)),
                ('ymin', models.CharField(max_length=50)),
                ('ymax', models.CharField(max_length=50)),
                ('reviewed', models.IntegerField()),
            ],
            options={
                'db_table': 'license_plates_rlvd',
            },
        ),
        migrations.CreateModel(
            name='ViolationRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('violation_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'violation_ref',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rlvd.licenseplatesrlvd')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rlvd.violationref')),
            ],
            options={
                'db_table': 'violations',
            },
        ),
        migrations.CreateModel(
            name='EvidenceCamImg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evidence_image', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rlvd.licenseplatesrlvd')),
            ],
            options={
                'db_table': 'evidence_cam_img',
            },
        ),
    ]
