# Generated by Django 3.2.6 on 2021-10-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlvd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvidenceCamImg',
        ),
        migrations.AddField(
            model_name='licenseplatesrlvd',
            name='evidence_images',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenseplatesrlvd',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenseplatesrlvd',
            name='speed_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenseplatesrlvd',
            name='violations',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Violation',
        ),
    ]
