# Generated by Django 3.2.6 on 2021-08-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rlvd', '0002_camera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidencecamimg',
            old_name='vehicle',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='violation',
            old_name='vehicle',
            new_name='entry',
        ),
    ]
