# Generated by Django 3.2.6 on 2022-01-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlvd', '0003_auto_20211101_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='anprcamera',
            name='http_port',
            field=models.IntegerField(default=9090),
            preserve_default=False,
        ),
    ]
