# Generated by Django 3.2.6 on 2021-12-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleColorRef',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'vehicle_color_ref',
            },
        ),
        migrations.CreateModel(
            name='VehicleMakeRef',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('type_id', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'vehicle_make_ref',
            },
        ),
        migrations.CreateModel(
            name='VehicleTypeRef',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'vehicle_type_ref',
            },
        ),
        migrations.CreateModel(
            name='VehicleModelRef',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anpr.vehiclemakeref')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anpr.vehicletyperef')),
            ],
            options={
                'db_table': 'vehicle_model_ref',
            },
        ),
        migrations.CreateModel(
            name='LicensePlatesAnpr',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('anpr_full_image', models.CharField(max_length=100)),
                ('anpr_cropped_image', models.CharField(max_length=100)),
                ('vehicle_color', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='anpr.vehiclecolorref')),
                ('vehicle_make', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='anpr.vehiclemakeref')),
                ('vehicle_model', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='anpr.vehiclemodelref')),
                ('vehicle_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='anpr.vehicletyperef')),
            ],
            options={
                'db_table': 'license_plates_anpr',
            },
        ),
    ]
