# Generated by Django 3.2.6 on 2021-09-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlatesAnpr',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('anpr_full_image', models.CharField(max_length=100)),
                ('anpr_cropped_image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'license_plates_anpr',
            },
        ),
    ]
