# Generated by Django 3.2.6 on 2021-10-31 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anpr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleColorRef',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'vehicle_color_ref',
            },
        ),
        migrations.CreateModel(
            name='VehicleMakeRef',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('type_id', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'vehicle_make_ref',
            },
        ),
        migrations.CreateModel(
            name='VehicleTypeRef',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'vehicle_type_ref',
            },
        ),
        migrations.CreateModel(
            name='VehicleModelRef',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anpr.vehiclemakeref')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anpr.vehicletyperef')),
            ],
            options={
                'db_table': 'vehicle_model_ref',
            },
        ),
        migrations.AddField(
            model_name='licenseplatesanpr',
            name='vehicle_color',
            field=models.ForeignKey(default='red', on_delete=django.db.models.deletion.DO_NOTHING, to='anpr.vehiclecolorref'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenseplatesanpr',
            name='vehicle_make',
            field=models.ForeignKey(default='tata', on_delete=django.db.models.deletion.DO_NOTHING, to='anpr.vehiclemakeref'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenseplatesanpr',
            name='vehicle_model',
            field=models.ForeignKey(default='suv', on_delete=django.db.models.deletion.DO_NOTHING, to='anpr.vehiclemodelref'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenseplatesanpr',
            name='vehicle_type',
            field=models.ForeignKey(default='mini', on_delete=django.db.models.deletion.DO_NOTHING, to='anpr.vehicletyperef'),
            preserve_default=False,
        ),
    ]
